import type { ExpenseItem } from "@/types/budget";

export const INITIAL_TOTAL_BUDGET = 30000;

export const INITIAL_EXPENSES: ExpenseItem[] = [
  {
    id: "transport",
    category: "Transportation",
    label: "Flights, train & long distance travel",
    amount: 5000,
    icon: "✈️",
    tone: "sky",
    min: 0,
    max: 25000,
    step: 500,
  },
  {
    id: "stay",
    category: "Accommodation",
    label: "Hotels, resorts & stay bookings",
    amount: 9000,
    icon: "🏨",
    tone: "peach",
    min: 0,
    max: 35000,
    step: 500,
  },
  {
    id: "food",
    category: "Food & Dining",
    label: "Cafes, restaurants & street food",
    amount: 3500,
    icon: "🍽️",
    tone: "butter",
    min: 0,
    max: 15000,
    step: 250,
  },
  {
    id: "activity",
    category: "Activities",
    label: "Tours, museum passes & sight tickets",
    amount: 2500,
    icon: "🎟️",
    tone: "mint",
    min: 0,
    max: 15000,
    step: 250,
  },
  {
    id: "local_transport",
    category: "Local Transport",
    label: "Cabs, metro & local transit",
    amount: 1500,
    icon: "🚕",
    tone: "lilac",
    min: 0,
    max: 10000,
    step: 250,
  },
  {
    id: "shopping",
    category: "Shopping",
    label: "Souvenirs, markets & gifts",
    amount: 2000,
    icon: "🛍️",
    tone: "blush",
    min: 0,
    max: 20000,
    step: 500,
  },
  {
    id: "emergency",
    category: "Emergency Fund",
    label: "Contingency reserve & medical buffer",
    amount: 3000,
    icon: "🛡️",
    tone: "surface",
    min: 0,
    max: 15000,
    step: 500,
  },
];
